apiVersion: v1
data:
  application.properties: |-
    spring.data.mongodb.host=mongodb.default
    spring.data.mongodb.database=demodb
    spring.data.mongodb.username=demoapp
    spring.data.mongodb.password=demoapp
kind: ConfigMap
metadata:
  name: mongodemo-config
